data:
  name: ACE
  root_path: /media/yanggang/847C02507C023D84/EventExtract/ace_2005_td_v7/data
  language: English
  mode: train
  train_subset: [nw, bn]
  dev_subset: [bc]
  test_subset: [cts, wl, un]
dataloader:
  batch_size: 1
  workers: 1
  shuffle: true
hyp:
  epoach: 100


